version: '3.8'

services:
  front:
    build: ./front
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - my_net

  backend:
    build: ./back
    container_name: backend
    ports:
      - "${BACKEND_PORT}:5000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    networks:
      - my_net
    depends_on:
      - database

  database:
    image: postgres:17.2
    container_name: database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - my_net
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: elestio/pgadmin
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin123@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    networks:
      - my_net

networks:
  my_net:
    driver: bridge

volumes:
  postgres_data: